### ISSUE TITLE
Not collecting any test case written in pytest

### ISSUE THREAD

**Issue by ankitkgupta09** [tfio/pytest-gui#3]
This tool is not collecting a test case written in Pytest.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\openscource\pytest-gui\view.py", line 605, in cmd_reload_tests
    self.reload_project(self.testdir_name.get())
  File "C:\openscource\pytest-gui\view.py", line 513, in reload_project
    self.project = self.load_project(self.root, self.Model, testdir)
  File "C:\openscource\pytest-gui\view.py", line 483, in project
    self._add_test_module('', testModule)
  File "C:\openscource\pytest-gui\view.py", line 453, in _add_test_module
    for testMethod_name, testMethod in sorted(testCase.items()):
AttributeError: 'TestMethod' object has no attribute 'items'

**Comment by fkreiner** [comment]
@ankitkgupta09  Any news on this? Did you manage to load pytest cases?

**Comment by ankitkgupta09** [comment]
@fkreiner No this did not work for me, is this work on unittest or pytest? my test cases are written using pytest.

**Comment by hmurari** [comment]
Sorry for the delay in response, I had missed the notification earlier. This was originally tested with tests written in unittest framework. Usually - we write all our test cases through unittest, and pytest just works seamlessly with those anyway. Can you point me to some sample pytest test cases where this is not working?

**Comment by fkreiner** [comment]
I tried some simple tests from the pytest examples

```
import pytest

def capital_case(x):
    return x.capitalize()

def test_capital_case():
    assert capital_case('semaphore') == 'Semaphore'

def test_raises_exception_on_non_string_arguments():
    with pytest.raises(TypeError):
        capital_case(9)
```

Pytest will execute those tests. pytest-gui does not show or execute them.
